# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-chat-activity
Version: 66
Release: %mkrel 1
Summary: Instant messaging client for Sugar
License: GPLv2+
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Chat/Chat-66.tar.bz2

Requires: python-simplejson  
Requires: sugar-toolkit >= 0.85.8

BuildRequires: gettext  
BuildRequires: sugar-toolkit >= 0.85.8

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
The Chat activity will provide a simple interface for collaborative discussion,
be it between two individuals or among a group as large as an entire classroom.
While a lightweight and 'impermanent' chat will be provided in a layer above
all activities and the various mesh levels, this activity devoted to textual
communication will keep detailed records of the conversation within the journal
and provide a means of searching through the conversation to locate
important comments.

%prep
%setup -q -n Chat-66


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.Chat

%clean
rm -rf %{buildroot}

%files -f org.laptop.Chat.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc AUTHORS COPYING NEWS

